replicaCount: 1
syncPeriod: 10m
enableLeaderElection: true

authSecret:
  enabled: true
  create: false
  name: "controller-manager"

dockerRegistryMirror: ""
image:
  repository: "summerwind/actions-runner-controller"
  actionsRunnerRepositoryAndTag: "summerwind/actions-runner:latest"
  dindSidecarRepositoryAndTag: "docker:dind"
  pullPolicy: IfNotPresent
  actionsRunnerImagePullSecrets: []

certManagerEnabled: true
imagePullSecrets: []

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 443

metrics:
  serviceMonitor: false
  port: 8443
  proxy:
    enabled: true
    image:
      repository: quay.io/brancz/kube-rbac-proxy
      tag: v0.11.0

podDisruptionBudget:
  enabled: false

scope:
  singleNamespace: false
  watchNamespace: ""

githubWebhookServer:
  enabled: false