aks_cluster_name = "Shared-Services"
aks_resource_group = "Shared-Services-RG"
aks_vnet_name = module.network_hub.virtual_network_name
aks_subnet_name = module.network_hub.default_subnet_name
dns_prefix = "shared-services-dns"
node_admin_username = "thesuper"
node_admin_ssh_pub_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC38OnsoHGWwpZaDALGEvdqPSDnCfNyWalKOuExRj8tIr+3LQIB8yOGxcR27R2Gv8hVCNYweV1QfRaN96gYwvq8Wa2gS+Te5VipOzjtiVLTwbL/4NIKv3OGdlVI2+UNmnkY3fYClZ/217DgTzmK3BxcbCKGy1XFVXbLtu4kPg5IW6fhcyLtbJCDHcVf7H+7dYjZZZtr5hHfyceWPzukYALCX5v3bqR8TuOqtBj7DddxVzhAnwA9AanIhDNtyUxoHHkZbo3tAN4UbdzAotA40hKLlrP1FVoPC95EK0eU5ZAB5xfyCJP3h81bOp6YevQxPyFKZ854+CmnPj5/GWPwxNo07lMG202ZHLRahGX91BjvHIwF9ZdhwBfVVLgQka06k8fXmgjpfHCWcttShWUdTfI+UkHctmMEgqGuz8zCBt5L+my4JL36db4/DZevMZ/eFJ5HfY7pd2Kzd7daazbNeP/4QsOIouWT13pES8F2yymil9RhBEyvPGwQZpb1Bop3Nms="
cluster_node_vm_size = "Standard_DS2_v2"